[DSPDC-1955] Fix retrying logic, add test (#221)
Why

Our retrying logic is busted; it doesn't actually retry but instead fails out immediately with an IllegalStateException:

java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()"

This PR

Closes the response prior to proceeding with the retry chain in the failure case
Adds a test around this code (😢 which should have been there in the first place)
Fixes the promise retry logic to not throw an Exception but rather fail the promise with an exception instance